name: Deploy Open API postman collection

on:
  pull_request:
    branches:
      - master
    types: [ closed ]

env:
  CI: true

jobs:
  generate-collection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install node modules
        run: npm ci --ignore-scripts

      - name: Build ABC & NAS specs
        run: npm run build:all

      - name: Deploy Open API Postman collection
        run: npm run postman

      - name: Clean up hard-coded IDs in Postman collection
        run: npm run postman_clean

      - uses: actions/upload-artifact@v2
        with:
          name: collection
          path: ./cko_collection_beta.json

  publish-collection:
    runs-on: ubuntu-latest
    needs: generate-collection
    steps:
      - name: Fetch checkout-postman repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
          repository: checkout/checkout-postman
          ref: main

      - uses: actions/download-artifact@v2
        with:
          name: collection

      - name: Commit collection
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"
          git branch -m "upload-postman-collection"
          git add cko_collection_beta.json
          git commit -m 'Upload new CKO collection'
          git push origin HEAD

      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.PAT}}
          script: |
            await github.pulls.create({
              owner: 'checkout',
              repo: 'checkout-postman',
              head: "upload-postman-collection",
              base: 'main',
              title: "Upload latest Checkout postman collection"
            });
            
