name: Create PR in upstream repo

on:
  push:
    branches:
      - 'master'

env:
  CI: true
  PAT: ${{ secrets.PAT }}

jobs:
  upload-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          repository: cko-payment-interfaces/checkout-api-reference
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Copy relevant files
        run: |
          echo "*** Creating newspec directory ***"
          mkdir -p newspec/{abc_spec,nas_spec}/{components/schemas,paths}
          echo "*** Copying files to newspec ***"
          cp -rv abc_spec/components/schemas/{HostedPayments,PaymentLinks} newspec/abc_spec/components/schemas
          cp -v abc_spec/paths/{hosted-payments*,payment-links*} newspec/abc_spec/paths
          cp -rv nas_spec/components/schemas/{HostedPayments,PaymentLinks} newspec/nas_spec/components/schemas
          cp -v nas_spec/paths/{hosted-payments*,payment-links*} newspec/nas_spec/paths
          echo "*** Listing contents of newspec ***"
          ls newspec/**/*
          echo "*** Ready to upload specs ***"

      - uses: actions/upload-artifact@v2
        with:
          name: specification
          path: newspec

  publish-spec:
    runs-on: ubuntu-latest
    needs: upload-spec
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: specification
          path: newspec

      - name: Fetch Checkout Api Reference repository
        uses: actions/checkout@v2
        with:
          repository: checkout/checkout-api-reference
          ref: master
          token: ${{ env.PAT }}
          path: api-reference

      - name: Commit Api specification
        working-directory: api-reference
        run: |
          git config user.email "payint-teamcity-cko@users.noreply.github.com" && git config user.name "payint-teamcity-cko"
          git checkout -b payment-interfaces/api-spec
          rsync -a ../newspec/abc_spec .
          rsync -a ../newspec/nas_spec .
          git add .
          git status
          git commit -m 'Publish new API Specification'
          git push origin HEAD

      - uses: actions/github-script@v5
        with:
          github-token: ${{ env.PAT }}
          script: |
            await github.rest.pulls.create({
              owner: 'checkout',
              repo: 'checkout-api-reference',
              head: "payint/Api-Spec",
              base: 'master',
              title: "Payment Interfaces: Update API Specification"
            });
